In [19]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

In [60]:
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size
        
        # Initialize weights randomly for the hidden layer and output
        self.weights1 = np.random.randn(self.input_size, self.hidden_size)
        self.weights2 = np.random.randn(self.hidden_size, self.output_size)
        self.bias1 = np.zeros((1, self.hidden_size))
        self.bias2 = np.zeros((1, self.output_size))

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self, X):
        # Calculate hidden layer
        self.hidden_layer = self.sigmoid(np.dot(X, self.weights1) + self.bias1)

        # Calculate output layer
        self.output_layer = self.sigmoid(
            np.dot(self.hidden_layer, self.weights2) + self.bias2
        )

        return self.output_layer

    def backpropagation(self, X, y, output):
        # Feed forward
        self.feedforward(X)
        
        # Menghitung error pada output layer
        output_error = y - output
        
        # Menghitung gradien pada output layer
        output_gradient = output_error * self.sigmoid_derivative(output)
        
        # Menghitung error pada layer tersembunyi
        hidden_error = np.dot(output_gradient, self.weights2.T)
        
        # Menghitung gradien pada layer tersembunyi
        hidden_gradient = hidden_error * self.sigmoid_derivative(self.hidden_layer)
        
        # Memperbarui bobot pada layer tersembunyi dan output
        self.weights2 += np.dot(self.hidden_layer.T, output_gradient) * learning_rate
        self.weights1 += np.dot(X.T, hidden_gradient) * learning_rate

    def train(self, X, y, num_epochs):
        for epoch in range(num_epochs):
            # Forward pass
            output = self.feedforward(X)

            # Backward pass
            self.backpropagation(X, y, output)

            # Calculate loss
            loss = np.mean(np.square(y - output))
            if epoch % 100 == 0:
                print("Epoch %d Loss: %.4f" % (epoch, loss))

    # def trainSGD(self, X, y, learning_rate, epochs):
    #     for epoch in range(epochs):
    #         for i in range(len(X)):
    #             x_i = X[i]
    #             y_i = y[i]
    #             mlp.backpropagation(x_i.reshape(1, -1), y_i.reshape(1, -1), learning_rate)
            
    #         # Cetak bobot setelah setiap epoch
    #         print(f"Epoch {epoch+1}:")
    #         mlp.show_weights()
    #         print("--------------------")

    def predict(self, X):
        return np.round(self.feedforward(X))
    
    def show_architecture(self):
        print("MLP Architecture:")
        print(f"Input layer: {self.input_size} neurons")
        print(f"Hidden layer: {self.hidden_size} neurons")
        print(f"Output layer: {self.output_size} neurons")
    
    def show_weights(self,epoch):
        print(f"Epoch ke: {epoch+1}")
        print("Bobot MLP:")
        print("W1:", self.weights1)
        print("W2:", self.weights2)

In [46]:
# # 2 input 4 hidden dan 1 output
# mlp = MLP(2, 4, 1)
# X = np.array([[0, 1]])  # Input
# y = np.array([[1]])     # Target output
# output = 1     # Learning rate
# # output = mlp.feedforward(X)
# mlp.backpropagation(X, y,output)
# # print("Output:", output)
# print("Updated weights:")
# print("W1:", mlp.weights1)
# print("W2:", mlp.weights2)

## Menggunakan Dataset Iris

In [61]:
iris = load_iris()
X = iris.data
y = iris.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Konversi label menjadi one-hot encoding
num_classes = len(np.unique(y))
y_train_encoded = np.eye(num_classes)[y_train]

# Inisialisasi dan melatih MLP
mlp = MLP(input_size=X_train.shape[1], hidden_size=4, output_size=num_classes)
learning_rate = 0.1
epochs = 10
# mlp.trainSGD(mlp,X_train, y_train_encoded, learning_rate, epochs)

for epoch in range(epochs):
    mlp.backpropagation(X_train, y_train_encoded, learning_rate)
    mlp.show_weights(epoch)
    print("--------------------")

# Evaluasi performa model pada data uji
y_pred = np.argmax(mlp.feedforward(X_test), axis=1)
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

Epoch ke: 1
Bobot MLP:
W1: [[-0.21938659  0.25884068  0.43629488  0.88466793]
 [ 0.34778726  0.23416242 -0.14807368 -1.79906437]
 [-0.76594992  1.09195099 -0.24026831 -0.76992225]
 [-2.60366939  1.27755224  2.10886911 -1.38988557]]
W2: [[ 0.45233559  1.09666929 -0.41894741]
 [-0.76996743  1.11663974  0.11955283]
 [-0.08237649 -0.25240515  0.60943081]
 [-0.93860573  0.77345433 -1.52810586]]
--------------------
Epoch ke: 2
Bobot MLP:
W1: [[-0.22200432  0.2782824   0.44719752  0.88608867]
 [ 0.30085681  0.16129761 -0.14268316 -1.83736066]
 [-0.75672197  1.13276119 -0.22766683 -0.75858159]
 [-2.60159677  1.30807812  2.12279204 -1.38519105]]
W2: [[ 0.76116463  1.15986188 -0.45593532]
 [-0.80853476  1.28091908  0.38420884]
 [-0.11850873 -0.08433371  0.86934998]
 [-0.79352435  0.95424131 -1.47219394]]
--------------------
Epoch ke: 3
Bobot MLP:
W1: [[-0.22581747  0.29913226  0.46365131  0.88378719]
 [ 0.25346971  0.07981427 -0.1489231  -1.87194606]
 [-0.74887833  1.17870837 -0.20506432 -0.75

In [37]:
def show_architecture(mlp):
    print("MLP Architecture:")
    print(f"Input layer: {mlp.input_size} neurons")
    print(f"Hidden layer: {mlp.hidden_size} neurons")
    print(f"Output layer: {mlp.output_size} neurons")
show_architecture(mlp)

MLP Architecture:
Input layer: 4 neurons
Hidden layer: 4 neurons
Output layer: 3 neurons
